import { useState, useEffect } from 'react';
import { HiDocumentArrowDown, HiUser, HiHeart, HiBeaker, HiChartBar, HiClock, HiSparkles } from 'react-icons/hi2';
import { fetchInsights } from '../services/chat';

export default function SummaryView({ user }) {
  const [insights, setInsights] = useState(null);
  const [aiSummary, setAiSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [loadingSummary, setLoadingSummary] = useState(false);
  const [recalculatingBMI, setRecalculatingBMI] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadInsights() {
      console.log('SummaryView: Loading insights for user', user?.id);
      try {
        const data = await fetchInsights(user?.id);
        console.log('SummaryView: Insights loaded successfully', data);
        setInsights(data);
        setError(null);
      } catch (error) {
        console.error('SummaryView: Failed to fetch insights:', error);
        setError('Failed to load insights');
      } finally {
        setLoading(false);
      }
    }
    loadInsights();
  }, [user?.id]);

  const handleGenerateSummary = async () => {
    setLoadingSummary(true);
    try {
      const response = await fetch(`http://localhost:8000/api/user/ai-summary?user_id=${user?.id || '00000000-0000-0000-0000-000000000001'}`);
      const data = await response.json();
      setAiSummary(data.summary);
    } catch (error) {
      console.error('Failed to generate AI summary:', error);
    } finally {
      setLoadingSummary(false);
    }
  };

  const handleRecalculateBMI = async () => {
    setRecalculatingBMI(true);
    try {
      const response = await fetch(`http://localhost:8000/api/user/recalculate-bmi?user_id=${user?.id || '00000000-0000-0000-0000-000000000001'}`, {
        method: 'POST'
      });
      const data = await response.json();
      
      if (data.error) {
        console.error('Failed to recalculate BMI:', data.error);
        return;
      }
      
      // Reload insights to get updated BMI
      const insightsResponse = await fetchInsights(user?.id);
      setInsights(insightsResponse);
      
      console.log('BMI recalculated:', data.bmi);
    } catch (error) {
      console.error('Failed to recalculate BMI:', error);
    } finally {
      setRecalculatingBMI(false);
    }
  };

  const handleDownload = () => {
    if (!aiSummary) return;

    // Create a printable HTML document
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>CogniFit Health Summary</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
          h1 { color: #10b981; text-align: center; margin-bottom: 10px; }
          .meta { text-align: center; color: #666; font-size: 14px; margin-bottom: 30px; }
          .user-info { margin-bottom: 30px; padding: 20px; background: #f9fafb; border-radius: 8px; }
          .summary { white-space: pre-wrap; line-height: 1.6; }
          .footer { text-align: center; color: #999; font-size: 12px; margin-top: 50px; }
        </style>
      </head>
      <body>
        <h1>CogniFit Health Summary</h1>
        <div class="meta">Generated: ${new Date().toLocaleDateString()}</div>
        <div class="user-info">
          <strong>User:</strong> ${insights?.user?.name || 'N/A'}<br>
          <strong>Age:</strong> ${insights?.user?.age || 'N/A'} | 
          <strong>Gender:</strong> ${insights?.user?.gender || 'N/A'}
        </div>
        <h2 style="color: #10b981;">AI-Generated Health Summary</h2>
        <div class="summary">${aiSummary}</div>
        <div class="footer">Generated by CogniFit Twin - AI-Powered Health Companion</div>
      </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  if (loading) {
    return (
      <div className="p-6 flex items-center justify-center h-full">
        <p className="text-text-muted">Loading summary...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6 flex items-center justify-center h-full flex-col gap-4">
        <p className="text-text-muted">{error}</p>
        <button 
          onClick={() => window.location.reload()}
          className="px-4 py-2 bg-primary text-white rounded-lg"
        >
          Retry
        </button>
      </div>
    );
  }

  if (!insights) {
    return (
      <div className="p-6 flex items-center justify-center h-full">
        <p className="text-text-muted">Failed to load summary</p>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6 max-w-5xl mx-auto">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="font-serif text-3xl text-text-main mb-2">
            Health Summary
          </h1>
          <p className="text-sm text-text-muted">
            AI-generated summary based on your conversation history
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleGenerateSummary}
            disabled={loadingSummary}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary text-white text-sm font-medium hover:bg-primary-hover transition-colors cursor-pointer disabled:opacity-50"
          >
            <HiSparkles className="text-base" />
            {loadingSummary ? 'Generating...' : 'Generate AI Summary'}
          </button>
          {aiSummary && (
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl border border-gray-200 text-text-main text-sm font-medium hover:bg-gray-50 transition-colors cursor-pointer"
            >
              <HiDocumentArrowDown className="text-base" />
              Download
            </button>
          )}
        </div>
      </div>

      {/* AI Summary Section */}
      {aiSummary ? (
        <div className="bg-white border border-gray-200 rounded-2xl p-6">
          <div className="flex items-center gap-3 mb-4">
            <HiSparkles className="text-primary text-xl" />
            <h3 className="text-lg font-semibold text-text-main">AI-Generated Health Summary</h3>
          </div>
          <div className="prose prose-sm max-w-none text-text-main whitespace-pre-line">
            {aiSummary}
          </div>
        </div>
      ) : (
        <div className="bg-gray-50 border border-gray-200 rounded-2xl p-8 text-center">
          <HiSparkles className="text-gray-400 text-4xl mx-auto mb-3" />
          <p className="text-text-muted mb-4">
            Click "Generate AI Summary" to analyze your conversation history and generate a comprehensive health report.
          </p>
          <p className="text-xs text-text-muted">
            The summary will include health issues discussed, lifestyle patterns, risk factors, AI advice given, and action items.
          </p>
        </div>
      )}

      {/* User Profile - Quick Reference */}
      <div className="bg-white border border-gray-200 rounded-2xl p-6">
        <div className="flex items-center gap-3 mb-4">
          <HiUser className="text-primary text-xl" />
          <h3 className="text-lg font-semibold text-text-main">Profile</h3>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          <div>
            <p className="text-xs text-text-muted">Name</p>
            <p className="text-sm font-medium text-text-main">{insights.user?.name || 'N/A'}</p>
          </div>
          <div>
            <p className="text-xs text-text-muted">Age</p>
            <p className="text-sm font-medium text-text-main">{insights.user?.age || 'N/A'}</p>
          </div>
          <div>
            <p className="text-xs text-text-muted">Gender</p>
            <p className="text-sm font-medium text-text-main">{insights.user?.gender || 'N/A'}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
